cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB